name: flutter_facebook_login
description: A Flutter plugin for allowing users to authenticate with native Android &amp; iOS Facebook login SDKs.
version: 3.0.0+1
homepage: https://github.com/roughike/flutter_facebook_login
publish_to: http://noah.tecarta.com:8100

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.roughike.facebooklogin.facebooklogin
        pluginClass: FacebookLoginPlugin
      ios:
        pluginClass: FacebookLoginPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"